services:
  moodle:
    image: public.ecr.aws/bitnami/moodle:latest
    ports:
      - '81:8080'
      - '444:8443'
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: seu-host-postgres.com
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: moodle_user
      MOODLE_DATABASE_PASSWORD: sua_senha_segura
      MOODLE_DATABASE_NAME: moodle_db
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: Admin@123
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITE_NAME: "Meu Moodle"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    restart: unless-stopped

volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
