services:
  moodle:
    image: public.ecr.aws/bitnami/moodle:latest
    ports:
      - '81:8080'
      - '444:8443'
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: laboratorio_moodle-postgres-db
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: postgres
      MOODLE_DATABASE_PASSWORD: 76c36b3f2dce4bf58be9
      MOODLE_DATABASE_NAME: laboratorio
      MOODLE_USERNAME: easjur
      MOODLE_PASSWORD: 76c36b3f2dce4bf58be9
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITE_NAME: "Moodle"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    restart: unless-stopped

volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
