services:
  moodle:
    image: bitnami/moodle:4.5.1
    ports:
      - "87:8080"
      - "444:8443"
    environment:
      MOODLE_DATABASE_HOST: "198.7.124.122"
      MOODLE_DATABASE_PORT_NUMBER: "3306"
      MOODLE_DATABASE_USER: "mariadb"
      MOODLE_DATABASE_PASSWORD: "bebb3466b9d00ff790dd" 
      MOODLE_DATABASE_NAME: "moodle"
      # ALLOW_EMPTY_PASSWORD não é mais necessário, pois definimos uma senha.
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    # depends_on não é necessário, pois não temos mais o mariadb no docker-compose
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
