services:
  moodle:
    image: public.ecr.aws/bitnami/moodle:latest
    ports:
      - '81:8080'
      - '444:8443'
    environment:
      MOODLE_DATABASE_HOST: laboratorio_moodle-db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodle_user
      MOODLE_DATABASE_PASSWORD: 3f4387e0fb5b40272c4c
      MOODLE_DATABASE_NAME: moodle_db
      MOODLE_USERNAME: easjur
      MOODLE_PASSWORD: dpdf@2024
      MOODLE_EMAIL: admin@example.com
      MOODLE_SITE_NAME: "Moodle"
    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    restart: unless-stopped

volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
